version: "3.8"

# ========================================
# DEVELOPMENT DOCKER COMPOSE
# ========================================
# ⚠️  This configuration is for LOCAL DEVELOPMENT only
#     Do not use in production environments

services:
  mongodb:
    image: mongo:7.0
    container_name: data-reader-mongodb-dev
    restart: unless-stopped
    labels:
      - "environment=development"
      - "purpose=data-reader-mongodb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: data-reader
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - data-reader-network
    command: mongod --auth

  mongo-express:
    image: mongo-express:1.0.0
    container_name: data-reader-mongo-express-dev
    restart: unless-stopped
    labels:
      - "environment=development"
      - "purpose=database-ui"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password123
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - data-reader-network

volumes:
  mongodb_data:
    driver: local
    labels:
      - "environment=development"
      - "purpose=mongodb-data"

networks:
  data-reader-network:
    driver: bridge
    labels:
      - "environment=development"
